# Generated by Django 5.0.4 on 2024-04-22 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
                ('cuerpo', models.TextField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.categorianoticia')),
                ('id_estado_noticia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.estadonoticia')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeRechazoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_rechazo', models.EmailField(max_length=200)),
                ('id_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('contrasenia', models.CharField(max_length=30)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPeriodista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.EmailField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.usuario'),
        ),
    ]
