# Generated by Django 5.0.4 on 2024-04-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaimagenes',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_noticias'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(default='portada.jpg', upload_to='portadas_noticias'),
        ),
        migrations.AddField(
            model_name='perfilperiodista',
            name='foto_perfil',
            field=models.ImageField(default='avatar-periodista.jpg', upload_to='foto_periodista'),
        ),
    ]
