# Generated by Django 5.0.4 on 2024-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galeriaimagenes_imagen_noticia_portada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=60)),
                ('asunto', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
