# Generated by Django 5.0.4 on 2024-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajerechazonoticia',
            name='mensaje_rechazo',
            field=models.CharField(max_length=200),
        ),
    ]
